### ISSUE TITLE
FATAL：SyntaxError: Unexpected token 'export'

### ISSUE THREAD

**Issue by JiHanHuang** [aiyoudiao/markdown-it-graphviz#2]
我想在我的hexo博客中使用这个插件。我在使用Markdown-it插件时，增加了你的这个组件。执行：`hexo g`的时候报错了：
```
/root/code/Blog/node_modules/_markdown-it-graphviz@1.1.2@markdown-it-graphviz/common/viz.es-changed.js:276
export default Viz;
^^^^^^

SyntaxError: Unexpected token 'export'
    at Module._compile (internal/modules/cjs/loader.js:892:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/root/code/Blog/node_modules/_markdown-it-graphviz@1.1.2@markdown-it-graphviz/index.js:14:13)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at /root/code/Blog/node_modules/hexo-renderer-markdown-it/lib/renderer.js:31:25
    at Array.reduce (<anonymous>)
    at Hexo.module.exports (/root/code/Blog/node_modules/hexo-renderer-markdown-it/lib/renderer.js:27:22)
    at Hexo.tryCatcher (/root/code/Blog/node_modules/bluebird/js/release/util.js:16:23)
    at Hexo.<anonymous> (/root/code/Blog/node_modules/bluebird/js/release/method.js:15:34)
    at /root/code/Blog/node_modules/hexo/lib/hexo/render.js:60:20
    at tryCatcher (/root/code/Blog/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/root/code/Blog/node_modules/bluebird/js/release/promise.js:517:31)
    at Promise._settlePromise (/root/code/Blog/node_modules/bluebird/js/release/promise.js:574:18)
```
多谢大佬。

**Comment by aiyoudiao** [comment]
抱歉，我现在才看到它，这个是因为你的工程不支持es6语法，优化工程中bable的配置应该就好了噢。如果还没有解决，可以加我微信 wx-aiyou-diao。



在 2021-01-25 12:15:54，"JiHan-" ***@***.***> 写道：

我想在我的hexo博客中使用这个插件。我在使用Markdown-it插件时，增加了你的这个组件。执行：hexo g的时候报错了：

***@***.***@markdown-it-graphviz/common/viz.es-changed.js:276

export default Viz;

^^^^^^



SyntaxError: Unexpected token 'export'

    at Module._compile (internal/modules/cjs/loader.js:892:18)

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)

    at Module.load (internal/modules/cjs/loader.js:812:32)

    at Function.Module._load (internal/modules/cjs/loader.js:724:14)

    at Module.require (internal/modules/cjs/loader.js:849:19)

    at require (internal/modules/cjs/helpers.js:74:18)

    at Object.<anonymous> ***@***.***@markdown-it-graphviz/index.js:14:13)

    at Module._compile (internal/modules/cjs/loader.js:956:30)

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)

    at Module.load (internal/modules/cjs/loader.js:812:32)

    at Function.Module._load (internal/modules/cjs/loader.js:724:14)

    at Module.require (internal/modules/cjs/loader.js:849:19)

    at require (internal/modules/cjs/helpers.js:74:18)

    at /root/code/Blog/node_modules/hexo-renderer-markdown-it/lib/renderer.js:31:25

    at Array.reduce (<anonymous>)

    at Hexo.module.exports (/root/code/Blog/node_modules/hexo-renderer-markdown-it/lib/renderer.js:27:22)

    at Hexo.tryCatcher (/root/code/Blog/node_modules/bluebird/js/release/util.js:16:23)

    at Hexo.<anonymous> (/root/code/Blog/node_modules/bluebird/js/release/method.js:15:34)

    at /root/code/Blog/node_modules/hexo/lib/hexo/render.js:60:20

    at tryCatcher (/root/code/Blog/node_modules/bluebird/js/release/util.js:16:23)

    at Promise._settlePromiseFromHandler (/root/code/Blog/node_modules/bluebird/js/release/promise.js:517:31)

    at Promise._settlePromise (/root/code/Blog/node_modules/bluebird/js/release/promise.js:574:18)



多谢大佬。
